import { z } from 'zod';

export const agentIdSchema = z.enum(['creator', 'narrator', 'market-maker', 'heartbeat']);
export type AgentId = z.infer<typeof agentIdSchema>;

export const agentStatusSchema = z.enum(['idle', 'running', 'done', 'error']);
export type AgentStatus = z.infer<typeof agentStatusSchema>;

// `bsc-testnet` retained for probe compatibility only; production path is `bsc-mainnet`
// per docs/decisions/2026-04-18-bsc-mainnet-pivot.md.
export const chainSchema = z.enum(['bsc-mainnet', 'bsc-testnet', 'base-sepolia', 'ipfs']);
export type Chain = z.infer<typeof chainSchema>;

export const txRefSchema = z.object({
  chain: chainSchema,
  hash: z.string(),
  label: z.string().optional(),
  explorerUrl: z.string().url(),
});
export type TxRef = z.infer<typeof txRefSchema>;

export const logEventSchema = z.object({
  ts: z.string().datetime(),
  agent: agentIdSchema,
  tool: z.string(),
  level: z.enum(['debug', 'info', 'warn', 'error']),
  message: z.string(),
  meta: z.record(z.unknown()).optional(),
});
export type LogEvent = z.infer<typeof logEventSchema>;

export const createRequestSchema = z.object({
  theme: z.string().min(3).max(280),
});
export type CreateRequest = z.infer<typeof createRequestSchema>;

export const tokenMetadataSchema = z.object({
  name: z.string(),
  symbol: z.string(),
  description: z.string(),
  imageLocalPath: z.string(),
  imageIpfsCid: z.string().optional(),
});
export type TokenMetadata = z.infer<typeof tokenMetadataSchema>;

export const creatorResultSchema = z.object({
  tokenAddr: z.string().regex(/^0x[a-fA-F0-9]{40}$/),
  tokenDeployTx: z.string(),
  loreIpfsCid: z.string(),
  metadata: tokenMetadataSchema,
});
export type CreatorResult = z.infer<typeof creatorResultSchema>;

// ---------------------------------------------------------------------------
// Artifacts — discriminated union of the five pill kinds shown in the web
// dashboard. Server-side demo orchestrators emit these through the SSE stream
// so the client renders the correct chain color + explorer link for each kind.
// See docs/decisions/2026-04-20-sse-and-runs-api.md for the shape rationale.
// ---------------------------------------------------------------------------

const evmAddressRegex = /^0x[a-fA-F0-9]{40}$/;
const evmTxHashRegex = /^0x[a-fA-F0-9]{64}$/;

export const bscTokenArtifactSchema = z.object({
  kind: z.literal('bsc-token'),
  chain: z.literal('bsc-mainnet'),
  address: z.string().regex(evmAddressRegex),
  explorerUrl: z.string().url(),
  label: z.string().optional(),
});

export const tokenDeployTxArtifactSchema = z.object({
  kind: z.literal('token-deploy-tx'),
  chain: z.literal('bsc-mainnet'),
  txHash: z.string().regex(evmTxHashRegex),
  explorerUrl: z.string().url(),
  label: z.string().optional(),
});

export const loreCidArtifactSchema = z.object({
  kind: z.literal('lore-cid'),
  cid: z.string().min(1),
  gatewayUrl: z.string().url(),
  author: z.enum(['creator', 'narrator']),
  chapterNumber: z.number().int().positive().optional(),
  label: z.string().optional(),
});

export const x402TxArtifactSchema = z.object({
  kind: z.literal('x402-tx'),
  chain: z.literal('base-sepolia'),
  txHash: z.string().regex(evmTxHashRegex),
  explorerUrl: z.string().url(),
  amountUsdc: z.string(), // decimal encoded as string to avoid float drift
  label: z.string().optional(),
});

export const tweetUrlArtifactSchema = z.object({
  kind: z.literal('tweet-url'),
  url: z.string().url(),
  tweetId: z.string().min(1),
  label: z.string().optional(),
});

// `meme-image` artifact (V2-P1) — Pinata-uploaded PNG generated by the Creator
// agent's `meme_image_creator` tool. Two-state shape:
//   - status === 'ok'           → cid + gatewayUrl populated, errorMessage absent
//   - status === 'upload-failed' → cid + gatewayUrl null, errorMessage required
// Pinata failure is non-fatal for the Creator flow: the tool emits the failed
// variant and the dashboard renders a placeholder card. The gatewayUrl must be
// an http(s) URL — base64 `data:` URLs are explicitly rejected because PNGs
// reach 1-2MB and would wedge SSE clients.
const httpsGatewayUrlSchema = z
  .string()
  .url()
  .refine((u) => /^https?:\/\//i.test(u), {
    message: 'gatewayUrl must be http(s); base64 data URLs are not permitted',
  });

// Single object schema with `.superRefine` enforces the two-state cross-field
// rules; we don't use `discriminatedUnion('status', ...)` because the outer
// `artifactSchema` already discriminates on `kind`, and zod forbids a kind
// literal appearing more than once in a discriminated union's option list.
export const memeImageArtifactSchema = z
  .object({
    kind: z.literal('meme-image'),
    status: z.enum(['ok', 'upload-failed']),
    cid: z.string().min(1).nullable(),
    gatewayUrl: z.union([httpsGatewayUrlSchema, z.null()]),
    prompt: z.string().min(1).max(1000),
    errorMessage: z.string().min(1).optional(),
    label: z.string().optional(),
  })
  .superRefine((value, ctx) => {
    if (value.status === 'ok') {
      if (value.cid === null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['cid'],
          message: 'cid required when status=ok',
        });
      }
      if (value.gatewayUrl === null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['gatewayUrl'],
          message: 'gatewayUrl required when status=ok',
        });
      }
    } else {
      if (value.cid !== null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['cid'],
          message: 'cid must be null when status=upload-failed',
        });
      }
      if (value.gatewayUrl !== null) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['gatewayUrl'],
          message: 'gatewayUrl must be null when status=upload-failed',
        });
      }
      if (value.errorMessage === undefined) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['errorMessage'],
          message: 'errorMessage required when status=upload-failed',
        });
      }
    }
  });

// `heartbeat-tick` artifact (V2-P3) — emitted once per tick the dashboard-
// driven Heartbeat run executes. Carries a 1-indexed `tickNumber` + fixed
// `totalTicks` so the UI can render `01 / 03 ticks` without having to know
// the cadence up front. `decisions` is an ordered trail of short-id decisions
// the agent took within this tick (e.g. ["check_status", "post"]); kept
// open-ended as strings because the tool choices are driven by LLM output.
export const heartbeatTickArtifactSchema = z
  .object({
    kind: z.literal('heartbeat-tick'),
    tickNumber: z.number().int().positive(),
    totalTicks: z.number().int().positive(),
    decisions: z.array(z.string()),
    label: z.string().optional(),
  })
  .superRefine((value, ctx) => {
    if (value.tickNumber > value.totalTicks) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['tickNumber'],
        message: 'tickNumber must be <= totalTicks',
      });
    }
  });

// `heartbeat-decision` artifact (V2-P3) — emitted when the Heartbeat agent
// resolves on a concrete action within a tick. `action` is constrained to the
// three outcomes the tick prompt allows; `reason` is the agent's short
// rationale and is always non-empty so the UI can render it verbatim in the
// decision tree.
export const heartbeatDecisionArtifactSchema = z.object({
  kind: z.literal('heartbeat-decision'),
  tickNumber: z.number().int().positive(),
  action: z.enum(['post', 'extend_lore', 'skip']),
  reason: z.string().min(1),
  label: z.string().optional(),
});

// `lore-anchor` artifact (AC3 on-chain anchor fallback) — emitted after the
// Narrator upserts a chapter into the LoreStore. Layer 1 (always on) carries
// a keccak256 `contentHash` commitment over
// `${tokenAddr}:${chapterNumber}:${loreCid}` plus the anchor bookkeeping
// fields. Layer 2 is an OPTIONAL zero-value self-tx memo on BSC mainnet,
// gated by the `ANCHOR_ON_CHAIN=true` env; when the tx lands we stamp the
// full `{onChainTxHash, chain, explorerUrl}` trio onto the artifact. The
// three fields are all-or-nothing so the UI never renders a half-built
// explorer link. The tx-hash regex matches the existing 32-byte EVM tx-hash
// convention used by `tokenDeployTxArtifactSchema` above.
const LORE_ANCHOR_CONTENT_HASH_REGEX = /^0x[a-fA-F0-9]{64}$/;
export const loreAnchorArtifactSchema = z
  .object({
    kind: z.literal('lore-anchor'),
    /** Deterministic unique key, shape `${tokenAddr-lowercased}-${chapterNumber}`. */
    anchorId: z.string().min(1),
    tokenAddr: z.string().min(1),
    chapterNumber: z.number().int().positive(),
    loreCid: z.string().min(1),
    /** 32-byte keccak256 commitment, 0x-prefixed lowercase hex. */
    contentHash: z.string().regex(LORE_ANCHOR_CONTENT_HASH_REGEX),
    ts: z.string().datetime(),
    /** Layer-2 on-chain trio. All three must be present together, or all absent. */
    onChainTxHash: z.string().regex(LORE_ANCHOR_CONTENT_HASH_REGEX).optional(),
    chain: z.literal('bsc-mainnet').optional(),
    explorerUrl: z.string().url().optional(),
    label: z.string().optional(),
  })
  .superRefine((value, ctx) => {
    const onChainFields = [value.onChainTxHash, value.chain, value.explorerUrl];
    const setCount = onChainFields.filter((v) => v !== undefined).length;
    if (setCount !== 0 && setCount !== 3) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['onChainTxHash'],
        message:
          'on-chain trio (onChainTxHash, chain, explorerUrl) must be all present or all absent',
      });
    }
  });

// `shill-order` artifact (Phase 4.6) — queue entry emitted when a creator
// pays 0.01 USDC via x402 to the `/shill/:tokenAddr` route. Status advances
// queued → processing → done / failed as the Shiller agent picks it up.
// `paidAmountUsdc` is a decimal-encoded string (matches `x402TxArtifactSchema`)
// to avoid float drift when the dashboard reads it back.
export const shillOrderArtifactSchema = z.object({
  kind: z.literal('shill-order'),
  orderId: z.string().min(1),
  targetTokenAddr: z.string().regex(evmAddressRegex),
  creatorBrief: z.string().optional(),
  paidTxHash: z.string().regex(evmTxHashRegex),
  paidAmountUsdc: z.string().min(1),
  status: z.enum(['queued', 'processing', 'done', 'failed']),
  ts: z.string().datetime(),
  label: z.string().optional(),
});

// `shill-tweet` artifact (Phase 4.6) — emitted once the Shiller agent posts
// the promotional tweet from its own X account. `tweetText` is capped at the
// 280-char X hard limit (internal target is ≤ 250 but the schema leaves
// headroom for edge cases). `orderId` correlates back to the source
// `shill-order` for the dashboard's order panel.
export const shillTweetArtifactSchema = z.object({
  kind: z.literal('shill-tweet'),
  orderId: z.string().min(1),
  targetTokenAddr: z.string().regex(evmAddressRegex),
  tweetId: z.string().min(1),
  tweetUrl: z.string().url(),
  tweetText: z.string().min(1).max(280),
  ts: z.string().datetime(),
  label: z.string().optional(),
});

// Note on `discriminatedUnion` vs `union`:
//   `memeImageArtifactSchema` + `heartbeatTickArtifactSchema` +
//   `loreAnchorArtifactSchema` are ZodEffects (they use `.superRefine`), which
//   `discriminatedUnion` cannot index by a literal `kind`. We keep the plain-
//   object kinds in the discriminated union (for narrowing + clearer zod
//   errors) and union the effects schemas on top. TypeScript's structural
//   narrow on `kind` still works on the resulting union because every branch
//   declares `kind` as a literal.
const baseArtifactSchema = z.discriminatedUnion('kind', [
  bscTokenArtifactSchema,
  tokenDeployTxArtifactSchema,
  loreCidArtifactSchema,
  x402TxArtifactSchema,
  tweetUrlArtifactSchema,
  heartbeatDecisionArtifactSchema,
  shillOrderArtifactSchema,
  shillTweetArtifactSchema,
]);

export const artifactSchema = z.union([
  baseArtifactSchema,
  memeImageArtifactSchema,
  heartbeatTickArtifactSchema,
  loreAnchorArtifactSchema,
]);
export type Artifact = z.infer<typeof artifactSchema>;
export type ArtifactKind = Artifact['kind'];

// ---------------------------------------------------------------------------
// Runs API — POST /api/runs + GET /api/runs/:id + GET /api/runs/:id/events.
// Phase 4 scope-limits `kind` to `a2a` only; `creator` and `heartbeat` slots
// are reserved for a follow-up without breaking the wire format.
// ---------------------------------------------------------------------------

export const runKindSchema = z.enum(['creator', 'a2a', 'heartbeat', 'shill-market']);
export type RunKind = z.infer<typeof runKindSchema>;

export const runStatusSchema = z.enum(['pending', 'running', 'done', 'error']);
export type RunStatus = z.infer<typeof runStatusSchema>;

export const createRunRequestSchema = z.object({
  kind: runKindSchema,
  params: z.record(z.unknown()).optional(),
});
export type CreateRunRequest = z.infer<typeof createRunRequestSchema>;

export const createRunResponseSchema = z.object({
  runId: z.string().min(1),
});
export type CreateRunResponse = z.infer<typeof createRunResponseSchema>;

export const runSnapshotSchema = z.object({
  runId: z.string().min(1),
  kind: runKindSchema,
  status: runStatusSchema,
  startedAt: z.string().datetime(),
  endedAt: z.string().datetime().optional(),
  artifacts: z.array(artifactSchema),
  logs: z.array(logEventSchema),
  errorMessage: z.string().optional(),
});
export type RunSnapshot = z.infer<typeof runSnapshotSchema>;

// ---------------------------------------------------------------------------
// SSE event payloads — each corresponds to an `event: <name>` field on the
// wire. Clients use EventSource.addEventListener(<name>, ...) to dispatch.
// A heartbeat comment line (`: ping`) is sent periodically by the server but
// carries no data payload and is invisible to EventSource handlers.
// ---------------------------------------------------------------------------

export const logEventPayloadSchema = logEventSchema;
export type LogEventPayload = LogEvent;

export const artifactEventPayloadSchema = artifactSchema;
export type ArtifactEventPayload = Artifact;

export const statusEventPayloadSchema = z.object({
  runId: z.string().min(1),
  status: runStatusSchema,
  errorMessage: z.string().optional(),
});
export type StatusEventPayload = z.infer<typeof statusEventPayloadSchema>;

// ---------------------------------------------------------------------------
// Fine-grained streaming events (V2-P2) — surface the Anthropic `messages.
// stream` internals the dashboard needs to stop feeling like "nothing is
// happening for 15 seconds". Three payload kinds:
//
//   tool_use:start      — tool invocation begun, input arguments resolved
//   tool_use:end        — tool finished (ok or error), server-side result
//   assistant:delta     — one chunk of assistant free-form text
//
// All three flow alongside (not instead of) the existing `log` and `artifact`
// events. LogEvent remains the coarse summary layer for post-mortem reads of
// the run; these new events drive live UI affordances (spinners, bubbles,
// token-by-token rendering).
// ---------------------------------------------------------------------------

export const toolUseStartEventPayloadSchema = z.object({
  agent: agentIdSchema,
  toolName: z.string().min(1),
  // `toolUseId` links the start spinner to its matching end result. Anthropic
  // guarantees these ids are unique per assistant turn; we treat them as
  // opaque strings.
  toolUseId: z.string().min(1),
  input: z.record(z.unknown()),
  ts: z.string().datetime(),
});
export type ToolUseStartEventPayload = z.infer<typeof toolUseStartEventPayloadSchema>;

export const toolUseEndEventPayloadSchema = z.object({
  agent: agentIdSchema,
  toolName: z.string().min(1),
  toolUseId: z.string().min(1),
  // Output is whatever the registered tool returned (after zod validation)
  // or `{ error: <message> }` when `isError` is true. Stringifying it is the
  // caller's job; we keep the raw shape so the UI can pretty-print.
  output: z.record(z.unknown()),
  isError: z.boolean(),
  ts: z.string().datetime(),
});
export type ToolUseEndEventPayload = z.infer<typeof toolUseEndEventPayloadSchema>;

export const assistantDeltaEventPayloadSchema = z.object({
  agent: agentIdSchema,
  // Non-empty by schema: the stream mapper drops empty-string deltas before
  // ever emitting, so seeing one on the wire signals an upstream regression.
  delta: z.string().min(1),
  ts: z.string().datetime(),
});
export type AssistantDeltaEventPayload = z.infer<typeof assistantDeltaEventPayloadSchema>;

export type SseEventName =
  | 'log'
  | 'artifact'
  | 'status'
  | 'tool_use:start'
  | 'tool_use:end'
  | 'assistant:delta';
